# Generated by Django 3.1.4 on 2021-01-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.department')),
            ],
        ),
    ]
