# Generated by Django 3.1.4 on 2021-01-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('pizza_topping', models.CharField(max_length=20)),
                ('pizza_sauce', models.CharField(max_length=20)),
                ('optional_extras', models.CharField(max_length=200)),
                ('delivery_instructions', models.TextField()),
            ],
        ),
    ]
